source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:deve

gem 'bson_ext'
gem 'mongo_mapper', '>= 0.13.1' 
gem 'sqlite3' # needed for initial start
gem 'aws-sdk', '~> 2' #used for image storage

#the authentication gem
gem 'devise' 
gem 'mm-devise'
#the authorization gem
gem 'pundit'

#css and javascript
gem 'foundation-rails', '5.4.5'


#gem for adding breadcrumbs
gem 'gretel'

#gem for managing environment variables
gem 'figaro'

#development gems
group :development, :test do 
  gem 'rspec-rails' 
  gem 'factory_girl_rails' 
end 
group :test do 
  gem 'faker' 
  gem 'capybara' 
  gem 'guard-rspec' 
  gem 'launchy'
  gem 'rails_layout' 
  gem 'database_cleaner'
end




#project specific gems
gem 'infusionsoft'
gem "jquery-fileupload-rails"

#gem to generate PDF
gem 'prawn'
gem 'pdfkit'

gem 'awesome_print'
gem 'wicked_pdf'
gem 'will_paginate'
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'





